"""Vouch tracking

Revision ID: 68042950fdc1
Revises: 7351aa8b16db
Create Date: 2024-09-14 05:01:35.287961+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68042950fdc1"
down_revision: Union[str, None] = "7351aa8b16db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vouches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voucher_id", sa.BigInteger(), nullable=True),
        sa.Column("receiver_id", sa.BigInteger(), nullable=True),
        sa.Column("approver_id", sa.BigInteger(), nullable=True),
        sa.Column("vouch_date", sa.DateTime(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vouches")
    # ### end Alembic commands ###
