"""Vouches store Interaction IDs

Revision ID: f66337b3b44b
Revises: 771f389c001a
Create Date: 2024-10-02 20:16:56.028113+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f66337b3b44b"
down_revision: Union[str, None] = "771f389c001a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vouches", sa.Column("interaction_id", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vouches", "interaction_id")
    # ### end Alembic commands ###
